In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [ ]:
import numpy as np
import pandas as pd


**Step 2: Importing dataset**

In [ ]:
df=pd.read_csv("/content/Data.csv")
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


**Step 3: Handling the missing data**

In [ ]:
df.isnull().sum()
# in the column (Age & Salary) one data is not an number!

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

**replacing the nan with median of those columns**

In [ ]:
df["Salary"].fillna(df["Salary"].median(),inplace=True)
df["Age"].fillna(df["Age"].median(),inplace=True)
df.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

**Step 4: Encoding categorical data**

In [ ]:
#Label encoding
from sklearn import preprocessing
df["Purchased"]=df[["Purchased"]].apply(preprocessing.LabelEncoder().fit_transform)
print(df)

   Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
4  Germany  40.0  61000.0          1
5   France  35.0  58000.0          1
6    Spain  38.0  52000.0          0
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1


**Step 5: Creating a dummy variable**

In [ ]:
onehotenc=pd.get_dummies(df)
onehotenc

Age   Salary  Purchased  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0          0               1                0              0
1  27.0  48000.0          1               0                0              1
2  30.0  54000.0          0               0                1              0
3  38.0  61000.0          0               0                0              1
4  40.0  61000.0          1               0                1              0
5  35.0  58000.0          1               1                0              0
6  38.0  52000.0          0               0                0              1
7  48.0  79000.0          1               1                0              0
8  50.0  83000.0          0               0                1              0
9  37.0  67000.0          1               1                0              0

**Step 6: Splitting the datasets into training sets and Test sets**

In [ ]:
features=onehotenc.drop("Purchased",axis=1)
target=onehotenc["Purchased"]
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size =0.3,random_state = 5)


**Step 7: Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler#import 
scaler=StandardScaler()#initialize
S_train=scaler.fit_transform(x_train)
S_test=scaler.transform(x_test)

In [ ]:
print("TRAINING SET:\n",S_train)
print("TESTING SET:\n",S_test)

TRAINING SET:
 [[-0.10052409 -0.33684515 -0.63245553  1.58113883 -0.8660254 ]
 [ 1.02534573  1.12668893  1.58113883 -0.63245553 -0.8660254 ]
 [-1.93006256 -1.39384198 -0.63245553 -0.63245553  1.15470054]
 [ 0.46241082  0.55753679  1.58113883 -0.63245553 -0.8660254 ]
 [ 1.30681319  1.45191873 -0.63245553  1.58113883 -0.8660254 ]
 [-0.38199155 -1.06861219 -0.63245553 -0.63245553  1.15470054]
 [-0.38199155 -0.33684515 -0.63245553 -0.63245553  1.15470054]]
TESTING SET:
 [[-0.52272528  0.15099955  1.58113883 -0.63245553 -0.8660254 ]
 [-0.80419273 -0.58076749  1.58113883 -0.63245553 -0.8660254 ]
 [-1.50786137 -0.90599729 -0.63245553  1.58113883 -0.8660254 ]]
